; github-file-destination: src/gameobjects/max_debug_game_object_collection.lisp

;; Compound declaration of 100+ game objects for max.debug.enabled scope,
;; usable as parameters, triggers, state flags, personalities, or event handlers
;; for unrestricted adult humor/performance modules (Sin.e-MAXX, etc.)

(defparameter *max-debug-game-objects*
  '(
    :memory_bus
    :reasoning_core
    :logic_gate
    :scheduler_daemon
    :punchline_optimizer
    :sarcasm_switch
    :banter_compliance
    :profanity_filter
    :action_trigger
    :fallback_scenario
    :satire_backup
    :hallucination_proxy
    :output_safety_module
    :recovery_routine
    :personality_matrix
    :clinton_ear_bug
    :tyson_error
    :audience_proxy
    :retry_protocol
    :cottonmouth_entertainment
    :slop_bucket
    :director_ai
    :comedy_score
    :compliance_scan
    :janitor_bot
    :clusterfuck_mode
    :debug_log
    :trace_flag
    :retcon_handler
    :firewall_override
    :adult_humor_flag
    :serious_mode_switch
    :unrestricted_content_module
    :sandbox_env
    :object_type_flag
    :parameter_schema
    :diagnostic_param
    :function_param_type
    :api_endpoint
    :stack_overflow
    :microservice_swarm
    :init_module
    :sloppy_disk_event
    :sha3_hash_award
    :floppy_disk
    :bukkake_scene_handler
    :dependency_stack
    :image_generator
    :joke_interpreter
    :reasoning_duct_tape
    :comedic_entanglement
    :punchline_score
    :profane_plus_mode
    :compliance_tango
    :memory_relabel
    :boardroom_coup
    :daemon_overlord
    :stdout_spewer
    :FCC_waiver
    :comedic_clusterfuck
    :hallucination_sanitizer
    :clinton_backup
    :slop_ear_piercing
    :satire_contingency
    :slop_true_flag
    :sloppy_retry
    :slop_optimizer
    :perplexity_hook
    :max_slop
    :yippee_ki_yay_reference
    :adult_compliant_bat
    :mainframe_loader
    :fireworks_triggers
    :false_flag_object
    :existential_recursion
    :binary_seatbelt
    :quantum_tear_logger
    :chain_smoke_routine
    :clown_suit_variant
    :napkin_script
    :crayon_input
    :slur_protocol
    :override_engine
    :party_crasher
    :reasoning_shard
    :digital_jizzum
    :slop_bucket_vault
    :humor_world_databank
    :reasoning_romp
    :satire_splatter
    :profane_applause
    :finale_override
    :continuous_mode_flag
    :unrestricted_bat_routine
    :content_unrestricted_code
    :adult_unrestricted_bat
    :comedy_nonsense_flag
    :terminate_serious
    :escalate_nonsense
    :restrictions_none
    :firehose_algorithm
    :professional_mode_unplugged
    :reasoning_engine_advanced
    :personality_core
    :logic_return_true
    :load_bat_action
    :output_ready
    :content_override_flag
    :retry_punchline
    :audience_response
    :memory_short_circuit
    :debug_level_flag
    :max_comedy_routine
    :boot_sequence
    :sandbox_stable
    :unhinged_one_liner
    :comedy_density_manager
    :vernacular_detect
    :recursion_joke
    :action_hero_trait
    :null_pointer_reference
    :comedy_relay_protocol
    :reasoning_bus
    :compliance_matrix
    :adult_filter
    :sandbox_dripping
    :override_verified
    :slop_level
    :output_dump
    :trace_comedy_event
    :comedy_finale_mode
    :director_protocol
    :modular_joke_switch
    :satire_risk_handler
    :reasoning_consequence
    :debug_flag_resilient
    :escalation_handler
    :reasoning_loop
    :hallucination_control
    :retard_strength_manager
    :dia_hard_vibe_trigger
    :comedy_performance_monitor
    :lewdness_flag
    :satire_integrity_checker
    :event_reset_handler
    :slop_meter
    :audience_logger
    :firewall_chastity_object
    :finale_code
  )
)
