name: ALN Secure Compliance Pipeline
on:
  push:
    branches: [main, 'release/**']
  pull_request:
    types: [opened, synchronize]

env:
  COMPLIANCE_MODE: 'PCI_DSS_v4.0'

jobs:
  pre-commit-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install ML Libraries
        run: |
          gem install sciruby
          gem install rumale

      - name: Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml

      - name: Run Ruby ML Compliance Checks
        run: |
          ruby scripts/ml_compliance.rb

      - name: Enforce Commit Policy
        run: |
          if grep -q 'secret' gitleaks-report.sarif && [ "${{ env.COMPLIANCE_MODE }}" = "PCI_DSS_v4.0" ]; then
            echo "::error ::Secret detected under PCI policy! Blocked."
            exit 1
          fi

  # Add any other jobs as needed, e.g., compliance checks, security audits, or release/publishing steps.
